name: flutter_terms_viewer
description: "The flutter_terms_viewer package offers a convenient widget for displaying Terms and Conditions, Privacy Policy, and other legal texts within Flutter apps. It provides a scrollable, user-friendly interface to view lengthy documents, making it easy to incorporate important legal information into your app's UI."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/flutter_terms_viewer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_symbols: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0